---
title: "d3part"
format: html
editor: visual
---

```{r}
library(tidyverse)
df_d3<-read.csv('/Users/anerimodi/Downloads/cleaned.csv')
```

You can add options to executable code like this

```{r}
df_d3$Time.of.Occurrence <- as.numeric(substr(df_d3$Time.of.Occurrence, 1, 2)) * 100 +
                          as.numeric(substr(df_d3$Time.of.Occurrence, 4, 5))
```

```{r}
df_d3["time_bin"] = cut(df_d3$Time.of.Occurrence, c(0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400), c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'), include.lowest=TRUE)
```

```{r}
df_d3<-df_d3 %>%
  group_by(time_bin, Vict.Sex)%>%
  summarise(prob=n(),
            .groups = 'drop')
```

```{r}
df_d3$prob<-(df_d3$prob)/620324
```

```{r}
df_d3$prob<-round(df_d3$prob,3)
```

```{r}
df_d3 <- df_d3 %>% pivot_wider(names_from = Vict.Sex, values_from = prob)
```

```{r}
df_d3
```

```{r}
write.csv(df_d3,"Safety.csv", row.names = FALSE) 
```
