---
title: "d3part"
format: html
editor: visual
---

```{r}
library(tidyverse)
df_d3<-read.csv('/Users/anerimodi/Downloads/cleaned.csv') #download the cleaned dataset
```

```{r}
df_d3$Time.of.Occurrence <- as.numeric(substr(df_d3$Time.of.Occurrence, 1, 2)) * 100 +
                          as.numeric(substr(df_d3$Time.of.Occurrence, 4, 5)) #converting time to continuous variable
```

```{r}
df_d3["time_bin"] = cut(df_d3$Time.of.Occurrence, c(0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400), c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'), include.lowest=TRUE) #binning the data into 24 hours
```

```{r}
df_d3<-df_d3 %>%
  group_by(time_bin, Vict.Sex)%>%
  summarise(prob=n(),
            .groups = 'drop') #grouping the data and counting the total crimes per time hour bin and sex of victime
```

```{r}
df_d4<-df_d3
df_d4<-df_d4 %>%
  group_by(time_bin)%>%
  summarise(total=sum(prob),
            .groups = 'drop') #grouping the data and counting the total crimes per time bin
```

```{r}
getval<-function(c1, data=df_d4) {
    data$total[data$time_bin==c1]} #function to retrieve the total from df_d4
```

```{r}
totals <- numeric(24)  #for each time bin, divide by the total of that time bin, to get the prob of that sex
for (i in 1:24) {
  totals[i] <- getval(i)
}
totals <- rep(totals, each = 2)

df_d3 <- cbind(df_d3, new_column = totals)
```

```{r}
df_d3$prob<-df_d3$prob/df_d3$new_column 
```

```{r}
df_d3 <- df_d3[, -which(names(df_d3) == "new_column")]
df_d3$prob<-round(df_d3$prob,3)
df_d3 <- df_d3 %>% pivot_wider(names_from = Vict.Sex, values_from = prob)
write.csv(df_d3,"Safety.csv", row.names = FALSE) 
```
